export const DISPLAY_PRODUCTS = "DISPLAY_PRODUCTS";
export const DISPLAY_PRODUCT = "DISPLAY_PRODUCT";
export const DISPLAY_CATEGORIES = "DISPLAY_CATEGORIES";

export const FETCH_START = "FETCH_START";
export const FETCH_FAILED = "FETCH_FAILED";